import Head from 'next/head'

const index = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta
        name='description'
        content='Generated by create next app'
      />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <h1>H1 Title</h1>
  </>
)

export default index
